@jwt = "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzA0NzcwMTh9.JOTtcbt3iE17x3ZS7nuSxiLoKLMpwlrIYO1-0a-7LX0"

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Admin 2",
  "email": "Admin2@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "Admin1@test.com",
  "password": "password"
}

###About Show
GET http://localhost:3000/abouts/1.json

###About update
PATCH http://localhost:3000/abouts/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "summary": "_____My name is Jordan Spaulding. I am the owner and operator of Jordan Spaulding Construction liscenced to work in California. I have been working on my building skills my whole life!"
}


###About destory
DELETE http://localhost:3000/abouts/1.json
Authorization: Bearer {{jwt}}

###portfolio Show
GET http://localhost:3000/portfolios/1.json

###portfolio update
PATCH http://localhost:3000/portfolios/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "job_name": "Pomona House"
}


###portfolio destory
DELETE http://localhost:3000/abouts/1.json
Authorization: Bearer {{jwt}}

###Woodshop Show
GET http://localhost:3000/woodshops/1.json

###Woodshop update
PATCH http://localhost:3000/woodshops/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "item": "Walnut Cutting Board"
}


###Woodshop destory
DELETE http://localhost:3000/abouts/1.json
Authorization: Bearer {{jwt}}
