### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Admin 1",
  "email": "Admin1@test.com",
  "password": "password",
  "password_confirmation": "password"
}